import type { Metadata } from "next";
import { Inter, Anybody } from "next/font/google";
import Providers from "@/components/providers";
import { Toaster } from "react-hot-toast";

import { cn } from "@/lib/utils";
import "./globals.css";

const fontSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});
const fontHeading = Anybody({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen antialiased font-brsonoma"
        )}
      >
        <Providers>
          <main>{children}</main>
          <Toaster position="bottom-center" />
        </Providers>
      </body>
    </html>
  );
}
